### ISSUE TITLE
Technetium or Technitium?

### ISSUE THREAD

**Issue by Node815** [Amateur-God/home-assistant-technitiumdns#12]
Not to be pedantic, but the spelling should be Technitium. (https://technitium.com/) 

It's not really a big issue, but just in case you were wanting to have some uniformity, this may be important.   I did find it to be a bit confusing when adding the entity to the dashboard when autocomplete didn't find anything with 'techni' but if I left off the 'i' it found it.  

Otherwise, it works well!  :)

**Comment by Amateur-God** [comment]
that's my bad, my grammar autocorrect keeps changing it to technetium and i kept forgetting to fix, i shall fix this in an upcoming update and hope it doesn't break stuff
