### ISSUE TITLE
Problem after upgrading to 2.2.1: Requirements for technitiumdns not found: ['aiohttp==3.10.0'].

### ISSUE THREAD

**Issue by rolf2222** [Amateur-God/home-assistant-technitiumdns#29]
# Problem/Motivation
After upgrading the the integration to version 2.2.1 it fails to start

## Expected behavior
Integration should successfully start

## Actual behavior
Integration does not start, error found in the HA log:
"Setup failed for custom integration 'technitiumdns': Requirements for technitiumdns not found: ['aiohttp==3.10.0']."
"ERROR (SyncWorker_5) [homeassistant.util.package] Unable to install package aiohttp==3.10.0: ERROR: Cannot install aiohttp==3.10.0 because these package versions have conflicting dependencies"

## Steps to reproduce
Restart HA

## Proposed changes
N/A

**Comment by Amateur-God** [comment]
This seems to be an issue where some people require 3.9.5 and some require 3.10.0 of aiohttp

Will look at a fix for this over the weekend. 

For now if you go to the integration page in HACS and click the 3 dots at top right then click redownload you can specify version 2.2.0 for download to fix this issue until I'm able to push a release to fix it

**Comment by Amateur-God** [comment]
@rolf2222 this should now be fixed in Version 2.2.0 i didn't get any errors while testing, but i also didn't get the error about the 3.10.0 update either so please re-open this issue with more logs if the error persists
