### ISSUE TITLE
Set sensor state class to `measurement` for statistics

### ISSUE THREAD

**Issue by IngmarStein** [Amateur-God/home-assistant-technitiumdns#34]
# Problem/Motivation

The statistics sensors don't set a state class. As a consequence, the numeric values are not shown as a line-chart but rather discrete values.

## Expected behavior

A chart similar to this one:
![Bildschirmfoto 2024-10-12 um 11 21 49](https://github.com/user-attachments/assets/c582df98-e1bf-4fb9-8494-365f820d13f2)

## Actual behavior

HA shows discrete values:
![Bildschirmfoto 2024-10-12 um 11 20 16](https://github.com/user-attachments/assets/d890746f-b39d-475c-8ec8-95c16d6e94af)

## Steps to reproduce

Open the details for any statistic sensor.

## Proposed changes

Set the `state_class` to `measurement` as per https://developers.home-assistant.io/docs/core/entity/sensor/

**Comment by Amateur-God** [comment]
Thank you for this i misunderstood it and thought they would just default to none with the line chart instead of discrete values

**Comment by Amateur-God** [comment]
this can be found in beta release @v2.3.0-Beta.3 if you would like to use it pre stable release

**Comment by IngmarStein** [comment]
Works like a charm, thank you!

**Comment by Amateur-God** [comment]
Just Re-Opening this while its in Beta so is easy to find for anyone else, will be auto closed on stable release of 2.3
