### ISSUE TITLE
Nothing more than 6 entities - No Logs/Data added

### ISSUE THREAD

**Issue by ThongSong7** [Amateur-God/home-assistant-technitiumdns#53]
https://github.com/Amateur-God/home-assistant-technitiumdns/issues/35#issue-2585926362

This is exactly the same for me.
VM in Proxmox - all things working for many years.
Verified that the connections are good, no VLANS, etc
Capable of making API Call via shell from HASSOS
No matter if NEW Admin account or any other user

I know it is difficult for you to reproduce this on your end, but I am not sure where to look to...
I do see when adding, it takes all of the timeout (presumably what you added as a workaround) limit to add into integration....
I have not done a WireShark due to a simple API call works.

Thanks in advance for your help....

**Comment by Amateur-God** [comment]
can you show logs of the timeouts please
